### ISSUE TITLE
make side filters on feed page work

### ISSUE THREAD

**Issue by agarg5** [eternagame/eternagame.org#100]

**Comment by agarg5** [comment]
@ktamas77 how can I get information for the numbers associated with the filters from the [endpoint](https://ktamas77.eternagame.org/home/swagger/index.html#/default/get_get__type_newsfeed)?:

![image](https://user-images.githubusercontent.com/45175645/82122726-8ecde180-9795-11ea-82f0-402c4dbbf867.png)

**Comment by agarg5** [comment]
@ktamas77 is the search enabled for this endpoint?

**Comment by luxaritas** [comment]
For context, the filters should be (based on the old site):
- all
- messages (this includes comments as well as DMs - it would be nice to have that split out at some point)
- news (we'll probably need a backend modification to make an option that returns BOTH news and blog posts)
- lab (specifies rewards for designing or voting on labs)
- groups

**Comment by luxaritas** [comment]
The numbers are supposed to represent the number of unread items from that category - but since everything is interleaved and we just have a timestamp for when you last viewed your feed to indicate whether you have unreads, I think it's best just to omit the numbers. I can't immediately determine a use case where they make sense. @sharife can try and convince me otherwise :)
