### ISSUE TITLE
Play/Puzzles - Right Column Filter/Sort

### ISSUE THREAD

**Issue by Tazzon77** [eternagame/eternagame.org#128]
Is it possible to have the right column content remain static/visible while scrolling?

**Comment by luxaritas** [comment]
The issue with this is that if your screen is too short, then you won't be able to access all the filters. This behavior is similar to sidebar filters on shopping websites for example. [Brourd brought this up](https://getsatisfaction.com/eternagame/topics/-new-site-infinite-scroll-logic-and-filters) and I suggested that we have a "back to top" button, since if you change the filters, it doesn't make sense to "keep your place" anyways. Thoughts?

**Comment by Tazzon77** [comment]
I get your point that changing filters midway would cause a refresh with entirely different content. Here's where I was coming from...sometimes after scrolling long distances, I absently "forget" what filters I have selected and just want to look (and not change) without having to scroll all the way back and thus lose my place. In other instances, I may start with "uncleared" and want to drill down further to, let's say, single state only. I understand all the work and other issues that "simple sounding ideas" can raise, so I am confident you will arrive at the best/most realistic solutions given more pressing priorities.

**Comment by luxaritas** [comment]
Closing in favor of #358
